/** Canonical Protestant canon book IDs (language-neutral). */
export const CANONICAL_BOOKS = [
  { id: "GEN", order: 1, chapters: 50, nameEn: "Genesis", testament: "OT" },
  { id: "EXO", order: 2, chapters: 40, nameEn: "Exodus", testament: "OT" },
  { id: "LEV", order: 3, chapters: 27, nameEn: "Leviticus", testament: "OT" },
  { id: "NUM", order: 4, chapters: 36, nameEn: "Numbers", testament: "OT" },
  { id: "DEU", order: 5, chapters: 34, nameEn: "Deuteronomy", testament: "OT" },
  { id: "JOS", order: 6, chapters: 24, nameEn: "Joshua", testament: "OT" },
  { id: "JDG", order: 7, chapters: 21, nameEn: "Judges", testament: "OT" },
  { id: "RUT", order: 8, chapters: 4, nameEn: "Ruth", testament: "OT" },
  { id: "1SA", order: 9, chapters: 31, nameEn: "1 Samuel", testament: "OT" },
  { id: "2SA", order: 10, chapters: 24, nameEn: "2 Samuel", testament: "OT" },
  { id: "1KI", order: 11, chapters: 22, nameEn: "1 Kings", testament: "OT" },
  { id: "2KI", order: 12, chapters: 25, nameEn: "2 Kings", testament: "OT" },
  { id: "1CH", order: 13, chapters: 29, nameEn: "1 Chronicles", testament: "OT" },
  { id: "2CH", order: 14, chapters: 36, nameEn: "2 Chronicles", testament: "OT" },
  { id: "EZR", order: 15, chapters: 10, nameEn: "Ezra", testament: "OT" },
  { id: "NEH", order: 16, chapters: 13, nameEn: "Nehemiah", testament: "OT" },
  { id: "EST", order: 17, chapters: 10, nameEn: "Esther", testament: "OT" },
  { id: "JOB", order: 18, chapters: 42, nameEn: "Job", testament: "OT" },
  { id: "PSA", order: 19, chapters: 150, nameEn: "Psalms", testament: "OT" },
  { id: "PRO", order: 20, chapters: 31, nameEn: "Proverbs", testament: "OT" },
  { id: "ECC", order: 21, chapters: 12, nameEn: "Ecclesiastes", testament: "OT" },
  { id: "SNG", order: 22, chapters: 8, nameEn: "Song of Solomon", testament: "OT" },
  { id: "ISA", order: 23, chapters: 66, nameEn: "Isaiah", testament: "OT" },
  { id: "JER", order: 24, chapters: 52, nameEn: "Jeremiah", testament: "OT" },
  { id: "LAM", order: 25, chapters: 5, nameEn: "Lamentations", testament: "OT" },
  { id: "EZK", order: 26, chapters: 48, nameEn: "Ezekiel", testament: "OT" },
  { id: "DAN", order: 27, chapters: 12, nameEn: "Daniel", testament: "OT" },
  { id: "HOS", order: 28, chapters: 14, nameEn: "Hosea", testament: "OT" },
  { id: "JOL", order: 29, chapters: 3, nameEn: "Joel", testament: "OT" },
  { id: "AMO", order: 30, chapters: 9, nameEn: "Amos", testament: "OT" },
  { id: "OBA", order: 31, chapters: 1, nameEn: "Obadiah", testament: "OT" },
  { id: "JON", order: 32, chapters: 4, nameEn: "Jonah", testament: "OT" },
  { id: "MIC", order: 33, chapters: 7, nameEn: "Micah", testament: "OT" },
  { id: "NAM", order: 34, chapters: 3, nameEn: "Nahum", testament: "OT" },
  { id: "HAB", order: 35, chapters: 3, nameEn: "Habakkuk", testament: "OT" },
  { id: "ZEP", order: 36, chapters: 3, nameEn: "Zephaniah", testament: "OT" },
  { id: "HAG", order: 37, chapters: 2, nameEn: "Haggai", testament: "OT" },
  { id: "ZEC", order: 38, chapters: 14, nameEn: "Zechariah", testament: "OT" },
  { id: "MAL", order: 39, chapters: 4, nameEn: "Malachi", testament: "OT" },
  { id: "MAT", order: 40, chapters: 28, nameEn: "Matthew", testament: "NT" },
  { id: "MRK", order: 41, chapters: 16, nameEn: "Mark", testament: "NT" },
  { id: "LUK", order: 42, chapters: 24, nameEn: "Luke", testament: "NT" },
  { id: "JHN", order: 43, chapters: 21, nameEn: "John", testament: "NT" },
  { id: "ACT", order: 44, chapters: 28, nameEn: "Acts", testament: "NT" },
  { id: "ROM", order: 45, chapters: 16, nameEn: "Romans", testament: "NT" },
  { id: "1CO", order: 46, chapters: 16, nameEn: "1 Corinthians", testament: "NT" },
  { id: "2CO", order: 47, chapters: 13, nameEn: "2 Corinthians", testament: "NT" },
  { id: "GAL", order: 48, chapters: 6, nameEn: "Galatians", testament: "NT" },
  { id: "EPH", order: 49, chapters: 6, nameEn: "Ephesians", testament: "NT" },
  { id: "PHP", order: 50, chapters: 4, nameEn: "Philippians", testament: "NT" },
  { id: "COL", order: 51, chapters: 4, nameEn: "Colossians", testament: "NT" },
  { id: "1TH", order: 52, chapters: 5, nameEn: "1 Thessalonians", testament: "NT" },
  { id: "2TH", order: 53, chapters: 3, nameEn: "2 Thessalonians", testament: "NT" },
  { id: "1TI", order: 54, chapters: 6, nameEn: "1 Timothy", testament: "NT" },
  { id: "2TI", order: 55, chapters: 4, nameEn: "2 Timothy", testament: "NT" },
  { id: "TIT", order: 56, chapters: 3, nameEn: "Titus", testament: "NT" },
  { id: "PHM", order: 57, chapters: 1, nameEn: "Philemon", testament: "NT" },
  { id: "HEB", order: 58, chapters: 13, nameEn: "Hebrews", testament: "NT" },
  { id: "JAS", order: 59, chapters: 5, nameEn: "James", testament: "NT" },
  { id: "1PE", order: 60, chapters: 5, nameEn: "1 Peter", testament: "NT" },
  { id: "2PE", order: 61, chapters: 3, nameEn: "2 Peter", testament: "NT" },
  { id: "1JN", order: 62, chapters: 5, nameEn: "1 John", testament: "NT" },
  { id: "2JN", order: 63, chapters: 1, nameEn: "2 John", testament: "NT" },
  { id: "3JN", order: 64, chapters: 1, nameEn: "3 John", testament: "NT" },
  { id: "JUD", order: 65, chapters: 1, nameEn: "Jude", testament: "NT" },
  { id: "REV", order: 66, chapters: 22, nameEn: "Revelation", testament: "NT" },
] as const;

export type CanonicalBookId = (typeof CANONICAL_BOOKS)[number]["id"];

/** USFM book codes → canonical IDs (common variants). */
export const USFM_TO_CANONICAL: Record<string, CanonicalBookId> = {
  GEN: "GEN",
  EXO: "EXO",
  LEV: "LEV",
  NUM: "NUM",
  DEU: "DEU",
  JOS: "JOS",
  JDG: "JDG",
  RUT: "RUT",
  "1SA": "1SA",
  "2SA": "2SA",
  "1KI": "1KI",
  "2KI": "2KI",
  "1CH": "1CH",
  "2CH": "2CH",
  EZR: "EZR",
  NEH: "NEH",
  EST: "EST",
  JOB: "JOB",
  PSA: "PSA",
  PS: "PSA",
  PRO: "PRO",
  ECC: "ECC",
  SNG: "SNG",
  SOS: "SNG",
  ISA: "ISA",
  JER: "JER",
  LAM: "LAM",
  EZK: "EZK",
  EZE: "EZK",
  DAN: "DAN",
  HOS: "HOS",
  JOL: "JOL",
  JOE: "JOL",
  AMO: "AMO",
  OBA: "OBA",
  JON: "JON",
  MIC: "MIC",
  NAM: "NAM",
  NAH: "NAM",
  HAB: "HAB",
  ZEP: "ZEP",
  HAG: "HAG",
  ZEC: "ZEC",
  MAL: "MAL",
  MAT: "MAT",
  MRK: "MRK",
  MAR: "MRK",
  LUK: "LUK",
  JHN: "JHN",
  JOH: "JHN",
  ACT: "ACT",
  ROM: "ROM",
  "1CO": "1CO",
  "2CO": "2CO",
  GAL: "GAL",
  EPH: "EPH",
  PHP: "PHP",
  PHI: "PHP",
  COL: "COL",
  "1TH": "1TH",
  "2TH": "2TH",
  "1TI": "1TI",
  "2TI": "2TI",
  TIT: "TIT",
  PHM: "PHM",
  HEB: "HEB",
  JAS: "JAS",
  JAM: "JAS",
  "1PE": "1PE",
  "2PE": "2PE",
  "1JN": "1JN",
  "2JN": "2JN",
  "3JN": "3JN",
  JUD: "JUD",
  REV: "REV",
};
